## 07. 세출 예산편성현황 데이터 분석

groupby를 이용한 집계(SQL의 GROUP BY 와 동일)
- 데이터프레임`.groupby('컬럼명')`
- 데이터프레임`.groupby('그룹화기준컬럼')['그룹화 대상 컬럼].집계함수`
- 데이터프레임.`sort_values('정렬기준컬럽',ascending = True | False)` 

데이터 차이 분석(정부안금액 - 국회확정금액 차이 col 추가)
- 데이터프레임`['신규컬럼명'] = 컬럼값`
- `세출예산편성_DF['차이금액'] = 세출예산편성_DF.정부안금액 - 세출예산편성_DF.국회확정금액`

IF 차이금액>0, 수입목명의 빈도 분석
- `pd.DataFrame(세출예산편성_DF[세출예산편성_DF.차이금액 < 0].수입목명.value_counts())`

세출 과목 분류별 분석
![세출 과목 분류별 분석 이미지](Practice%20Data/세출분류명.png)
- `apply()` 함수를 이용한 세입 과목 분류표 적용 및 신규 컬럼 생성

iloc를 이용한 컬럼 행출력 순서 지정(특정 행 추출, 행과열 순서 변경 가능)
- 데이터프레임`.iloc[[0,2,3,1],:]` (행 순서 변경)
- 데이터프레임`.iloc[행인덱스, 열인덱스]`

axis=0 vs axis=1
- `axis=0` : 열단위, 모든 행의 평균이나 열별 합계 구할 때
- `axis=1` : 행단위, 여러 열을 조합해서 새로운 값 만들 때

In [2]:
!pip3 install pandas
!pip3 install koreanize_matplotlib
!pip3 install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: koreanize_matplotlib in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (0.1.1)
Requirement already satisfied: matplotlib in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from koreanize_matplotlib) (3.9.4)
Requirement already satisfied: pillow>=8 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (11.3.0)
Requirement already satisfied: packaging>=20.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (26.0)
Requirement already satisfied: cycler>=0.10 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (0.12.1)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (3.3.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (6.5.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (1.3.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (1.4.7)
Requirement already satisfied: python-dateutil>=2.7 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (2.9.0.post0)
Requirement already satisfied: numpy>=1.23 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (2.0.2)
Requirement already satisfied: fonttools>=4.22.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (4.60.2)
Requirement already satisfied: zipp>=3.1.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib->koreanize_matplotlib) (3.23.0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->koreanize_matplotlib) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (0.13.2)
Requirement already satisfied: pandas>=1.2 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from seaborn) (3.9.4)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from seaborn) (2.0.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: contourpy>=1.0.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (6.5.2)
Requirement already satisfied: pillow>=8 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.2)
Requirement already satisfied: packaging>=20.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: cycler>=0.10 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: zipp>=3.1.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.23.0)
Requirement already satisfied: pytz>=2020.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

# 과학적 표기법 해제
pd.options.display.float_format = '{:.0f}'.format

세입예산편성_DF = pd.read_csv("Practice Data/세입_예산편성현황_2024.csv")
세출예산편성_DF = pd.read_csv("Practice Data/세출_예산편성현황_2024.csv")


# 컬럼명 변경
세출예산편성_DF.rename(columns = {'정부안금액(천원)' : '정부안금액', '국회확정금액(천원)':'국회확정금액'}, inplace=True)
print(pd.DataFrame(세출예산편성_DF[-5:]))

# 컴마 제거, 문자열 데이터 숫자 변환(정부안금액/국회확정금액)
세출예산편성_DF.정부안금액 = 세출예산편성_DF.정부안금액.str.replace(',', '')
세출예산편성_DF.국회확정금액 = 세출예산편성_DF.국회확정금액.str.replace(',', '')

세출예산편성_DF.정부안금액 = pd.to_numeric(세출예산편성_DF.정부안금액)
세출예산편성_DF.국회확정금액 = pd.to_numeric(세출예산편성_DF.국회확정금액)

print(세출예산편성_DF.info())

         No.  회계년도  소관명       회계명  계정명 분야명   부문명         프로그램명    단위사업명  \
41438  41439  2024  환경부  환경개선특별회계  NaN  환경  환경일반         회계간거래    회계간전출
41439  41440  2024  환경부  환경개선특별회계  NaN  환경  환경일반         회계간거래    회계간전출
41440  41441  2024  환경부  환경개선특별회계  NaN  환경  환경일반         회계간거래    회계간전출
41441  41442  2024  환경부  환경개선특별회계  NaN  환경  환경일반  회계기금간거래(전출금)  회계기금간거래
41442  41443  2024  환경부  환경개선특별회계  NaN  환경  환경일반  회계기금간거래(전출금)  회계기금간거래

                          세부사업명          경비구분               지출구분    목명  \
41438  지역균형발전특별회계(제주특별자치도계정) 전출  주요사업비(기금사업비)      내부거래지출(회계간거래)  전출금등
41439     지역균형발전특별회계(지역자율계정) 전출  주요사업비(기금사업비)      내부거래지출(회계간거래)  전출금등
41440     지역균형발전특별회계(지역지원계정) 전출  주요사업비(기금사업비)      내부거래지출(회계간거래)  전출금등
41441      공무원연금기금 전출(공무원연금부담금)  주요사업비(기금사업비)  내부거래지출(예산=>기금간거래)  전출금등
41442               석면피해구제기금 전출  주요사업비(기금사업비)  내부거래지출(예산=>기금간거래)  전출금등

           세목명          정부안금액         국회확정금액
41438  특별회계전출금     31,214,000     31,214,000
41439  특별회계전출금    405,490,000    405,490,000
41440  특별회계전출금  1,251,221,000  1,281,593,000
41441    기금전출금     22,759,000     22,759,000
41442    기금전출금     12,000,000     12,000,000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41443 entries, 0 to 41442
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   No.     41443 non-null  int64
 1   회계년도    41443 non-null  int64
 2   소관명     41443 non-null  object
 3   회계명     41443 non-null  object
 4   계정명     5735 non-null   object
 5   분야명     41443 non-null  object
 6   부문명     41443 non-null  object
 7   프로그램명   41443 non-null  object
 8   단위사업명   41443 non-null  object
 9   세부사업명   41443 non-null  object
 10  경비구분    41443 non-null  object
 11  지출구분    41443 non-null  object
 12  목명      41443 non-null  object
 13  세목명     41443 non-null  object
 14  정부안금액   41443 non-null  int64
 15  국회확정금액  41443 non-null  int64
dtypes: int64(4), object(12)
memory usage: 5.1+ MB
None

In [4]:
#세출 예산편성 정부안금액 > 0, 국회확정금액 > 0 | 특정col의 합계 계산
print(len(세출예산편성_DF[(세출예산편성_DF.정부안금액==0) & (세출예산편성_DF.국회확정금액 > 0)]))
print(세출예산편성_DF[(세출예산편성_DF.정부안금액==0) & (세출예산편성_DF.국회확정금액 > 0)]['국회확정금액'].sum())

524
1881955439

In [5]:
# 소관명 빈도 분석 및 빈도 비율 분석
print(pd.DataFrame(세출예산편성_DF.소관명.value_counts()))

# 위에서 과학적 표기법으로 정수형태로 반환하였기에, 특정 코드에서만 임시로 보이게 설정해줘야함.
# 이 블록 안에서만 소수점 4자리로 출력함
with pd.option_context('display.float_format','{:.4}'.format):  
    print(pd.DataFrame(세출예산편성_DF.소관명.value_counts(normalize=True))[:10])

                     count
소관명
보건복지부                 2197
문화체육관광부               2124
환경부                   2078
국토교통부                 2078
과학기술정보통신부             1799
...                    ...
고위공직자범죄수사처              55
진실·화해를위한과거사정리위원회        35
국가교육위원회                 30
5·18민주화운동 진상규명조사위원회     25
국가정보원                    1

[61 rows x 1 columns]
           proportion
소관명
보건복지부         0.05301
문화체육관광부       0.05125
환경부           0.05014
국토교통부         0.05014
과학기술정보통신부     0.04341
해양수산부         0.04213
국방부           0.04095
행정안전부         0.04063
기획재정부         0.03815
방위사업청         0.03752

In [6]:
# 소관명별 정부안금액 합계
소관별_세출_정부안금액 = pd.DataFrame(세출예산편성_DF.groupby('소관명')['정부안금액'].sum())
소관별_세출_정부안금액.sort_values('정부안금액', ascending=False)
 
# 소관명별 국회확정금액 합계
소관별_세출_국회확정금액 = pd.DataFrame(세출예산편성_DF.groupby('소관명')['국회확정금액'].sum())
소관별_세출_국회확정금액.sort_values('국회확정금액', ascending=False)

                           국회확정금액
소관명
기획재정부                577064756000
보건복지부                246559177000
국토교통부                145370361000
교육부                  123312822000
행정안전부                 72447356000
...                           ...
민주평화통일자문회의               34974000
고위공직자범죄수사처               20680100
진실·화해를위한과거사정리위원회         16749000
국가교육위원회                  10279000
5·18민주화운동 진상규명조사위원회       6888000

[61 rows x 1 columns]

In [8]:
# 정부안금액 및 국회확정금액 차이 분석 + new column 생성
세출예산편성_DF['차이금액'] = 세출예산편성_DF.정부안금액 - 세출예산편성_DF.국회확정금액
세출예산편성_DF.head()

,No.,회계년도,소관명,회계명,계정명,분야명,부문명,프로그램명,단위사업명,세부사업명,경비구분,지출구분,목명,세목명,정부안금액,국회확정금액,차이금액
0,1,2024,5·18민주화운동 진상규명조사위원회,일반회계,NaN,일반·지방행정,일반행정,518 진상규명조사위원회 운영,518 진상규명 지원,518 진상규명지원,주요사업비(기금사업비),일반지출,건설비,공사비,176770,176770,0
1,2,2024,5·18민주화운동 진상규명조사위원회,일반회계,NaN,일반·지방행정,일반행정,518 진상규명조사위원회 운영,518 진상규명 지원,518 진상규명지원,주요사업비(기금사업비),일반지출,건설비,실시설계비,18000,18000,0
2,3,2024,5·18민주화운동 진상규명조사위원회,일반회계,NaN,일반·지방행정,일반행정,518 진상규명조사위원회 운영,518 진상규명 지원,518 진상규명지원,주요사업비(기금사업비),일반지출,보전금,포상금,29700,29700,0
3,4,2024,5·18민주화운동 진상규명조사위원회,일반회계,NaN,일반·지방행정,일반행정,518 진상규명조사위원회 운영,518 진상규명 지원,518 진상규명지원,주요사업비(기금사업비),일반지출,업무추진비,관서업무추진비,41000,41000,0
4,5,2024,5·18민주화운동 진상규명조사위원회,일반회계,NaN,일반·지방행정,일반행정,518 진상규명조사위원회 운영,518 진상규명 지원,518 진상규명지원,주요사업비(기금사업비),일반지출,여비,국내여비,321000,321000,0

In [9]:
#세부사업별 세출 축소 금액
세부사업별_차이금액_축소 = pd.DataFrame(세출예산편성_DF[세출예산편성_DF.차이금액 >0].groupby('세부사업명')['차이금액'].sum())[:10]
세부사업별_차이금액_축소.sort_values('차이금액',ascending=False)

                         차이금액
세부사업명
F-X 2차              230130000
K-콘텐츠 펀드 출자          20000000
KDX-Ⅱ 성능개량            6000000
K21보병전투차량 2차          5000000
425사업(R&D)            1364000
5-2생활권 복합커뮤니티센터 건립    1296000
DMZ 평화적 이용             200000
ICT 창의기업 육성            100000
G20 글로벌 거버넌스 대응 강화      62000
가족등록업무전산화(정보화)          10000

In [11]:
#세부사업별 세출 확대 금액
세부사업별_차이금액_확대 = pd.DataFrame(세출예산편성_DF[세출예산편성_DF.차이금액 < 0].groupby('세부사업명')['차이금액'].sum())[:10]
세부사업별_차이금액_확대.sort_values('차이금액',ascending=True)

                                     차이금액
세부사업명
ICT융합스마트공장보급확산                  -10000000
AI기반 어장 공간정보 빅데이터 플랫폼 구축 및 활용    -3500000
EV용 고에너지밀도 리튬이온전지 화재안전성 평가 기반구축  -3500000
3D프린팅 산업육성 기반 구축                 -3000000
EV배터리 접합기술 실증기반 구축               -1500000
EBS프로그램제작지원                      -1236000
CCUS클러스터 구축 타당성 조사 용역             -500000
F-X 2차                            -130000
IOT기반 함정정비 통합관제 플랫폼 개발(R&D)       -106000
155mm사거리연장탄                        -10000

In [16]:
소관별_차이금액 = pd.DataFrame(세출예산편성_DF.groupby('소관명')['차이금액'].sum())
소관별_차이금액.sort_values('차이금액',ascending=False)[:10]

                  차이금액
소관명
기획재정부        686887000
금융위원회        557620000
방위사업청        145330000
보건복지부        103655000
외교부           98967000
농림축산식품부       84430000
환경부           53399000
국방부           23124000
국세청           20255000
행정중심복합도시건설청   14456000

In [19]:
# 세출과목 분류표(한국재정정보원, 2024 회계기금운용기준)

def 세출과목유형(st):
    if st == '일반지출':
        return st
    elif st == '보전지출':
        return '보전지출, 여유자금운용'
    else:
        return '정부내부지출및기타'
    
세출예산편성_DF['세출과목유형'] = 세출예산편성_DF.지출구분.apply(세출과목유형)
세출예산편성_DF[:5]

,No.,회계년도,소관명,회계명,계정명,분야명,부문명,프로그램명,단위사업명,세부사업명,경비구분,지출구분,목명,세목명,정부안금액,국회확정금액,차이금액,세출과목유형
0,1,2024,5·18민주화운동 진상규명조사위원회,일반회계,NaN,일반·지방행정,일반행정,518 진상규명조사위원회 운영,518 진상규명 지원,518 진상규명지원,주요사업비(기금사업비),일반지출,건설비,공사비,176770,176770,0,일반지출
1,2,2024,5·18민주화운동 진상규명조사위원회,일반회계,NaN,일반·지방행정,일반행정,518 진상규명조사위원회 운영,518 진상규명 지원,518 진상규명지원,주요사업비(기금사업비),일반지출,건설비,실시설계비,18000,18000,0,일반지출
2,3,2024,5·18민주화운동 진상규명조사위원회,일반회계,NaN,일반·지방행정,일반행정,518 진상규명조사위원회 운영,518 진상규명 지원,518 진상규명지원,주요사업비(기금사업비),일반지출,보전금,포상금,29700,29700,0,일반지출
3,4,2024,5·18민주화운동 진상규명조사위원회,일반회계,NaN,일반·지방행정,일반행정,518 진상규명조사위원회 운영,518 진상규명 지원,518 진상규명지원,주요사업비(기금사업비),일반지출,업무추진비,관서업무추진비,41000,41000,0,일반지출
4,5,2024,5·18민주화운동 진상규명조사위원회,일반회계,NaN,일반·지방행정,일반행정,518 진상규명조사위원회 운영,518 진상규명 지원,518 진상규명지원,주요사업비(기금사업비),일반지출,여비,국내여비,321000,321000,0,일반지출

In [20]:
세출과목유형별금액 = pd.DataFrame(세출예산편성_DF.groupby('세출과목유형')['국회확정금액'].sum()/100000)
세출과목유형별금액.국회확정금액 = round(세출과목유형별금액.국회확정금액)
세출과목유형별금액

              국회확정금액
세출과목유형
보전지출, 여유자금운용 4570814
일반지출         6720671
정부내부지출및기타    4441589

In [21]:
세출과목유형별금액.iloc[[1,2,0],:]

              국회확정금액
세출과목유형
일반지출         6720671
정부내부지출및기타    4441589
보전지출, 여유자금운용 4570814