## 재정데이터를 활용한 분석 실습(1)

- 목적 : 지방자치단체별 일일 분야별 세출현황을 통한 예산액에 대한 시사점 도출

- 방법 : 예산현액과 지출액의 차이를 계산해 파생변수 '차액' 생성 / 지방자치단체 중 '서울'만 추출 / '서울' 지역에 따른 '분야명'을 기준으로 차액 비교 시각화

- 분석 데이터셋 : 분야별 세출현황(3년간, 2021~2023년) 데이터셋 (출처 : 열린재정, 지방재정 365)

In [1]:
!pip3 install pandas
!pip3 install koreanize_matplotlib
!pip3 install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: pytz>=2020.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: koreanize_matplotlib in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (0.1.1)
Requirement already satisfied: matplotlib in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from koreanize_matplotlib) (3.9.4)
Requirement already satisfied: python-dateutil>=2.7 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (2.9.0.post0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (1.4.7)
Requirement already satisfied: fonttools>=4.22.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (4.60.2)
Requirement already satisfied: pillow>=8 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (11.3.0)
Requirement already satisfied: cycler>=0.10 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (0.12.1)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (6.5.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (1.3.0)
Requirement already satisfied: packaging>=20.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (26.0)
Requirement already satisfied: numpy>=1.23 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (2.0.2)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib->koreanize_matplotlib) (3.3.2)
Requirement already satisfied: zipp>=3.1.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib->koreanize_matplotlib) (3.23.0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->koreanize_matplotlib) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from seaborn) (3.9.4)
Requirement already satisfied: fonttools>=4.22.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.2)
Requirement already satisfied: cycler>=0.10 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: packaging>=20.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: python-dateutil>=2.7 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (6.5.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: pillow>=8 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: zipp>=3.1.0 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.23.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: pytz>=2020.1 in /Users/jiyeon/Library/Python/3.9/lib/python/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [ ]:
## 2021년 세출현황 데이터셋 전처리

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 과학적 표기법 해제
pd.options.display.float_format = '{:.0f}'.format

df1 = pd.read_csv("Practice Data/분야별 세출현황_2021.csv")
df1.info() #결측치 없음

df1 = df1[['회계연도','지역명','분야명','예산현액','지출액']]
df1.head()

# 특정 컬럼의 항목('서울') 추출
df1[df1['지역명'] == '서울' ]
df1['지역명'].unique()
df1.head()

# 파생변수 만들기
df1['차액'] = df1['예산현액'] - df1['지출액']
df1.head()

# 필요한 컬럼만 추출(2)
df1 = df1[['회계연도','분야명','차액']]
df1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3179 entries, 0 to 3178
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   No        3179 non-null   int64
 1   회계연도      3179 non-null   int64
 2   지역명       3179 non-null   object
 3   자치단체코드    3179 non-null   int64
 4   자치단체명_한글  3179 non-null   object
 5   분야코드      3179 non-null   int64
 6   분야명       3179 non-null   object
 7   집행일자      3179 non-null   int64
 8   예산현액      3179 non-null   float64
 9   지출액       3179 non-null   float64
dtypes: float64(2), int64(5), object(3)
memory usage: 248.5+ KB

   회계연도      분야명            차액
0  2021   일반공공행정 5421150000000
1  2021  공공질서및안전 1316071000000
2  2021       교육 2812276000000
3  2021    문화및관광  538381000000
4  2021       환경  800218000000

In [13]:
## 2022년 세출현황 데이터셋 전처리

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 과학적 표기법 해제
pd.options.display.float_format = '{:.0f}'.format

df2 = pd.read_csv("Practice Data/분야별 세출현황_2022.csv")
df2.info() #결측치 없음

df2 = df2[['회계연도','지역명','분야명','예산현액','지출액']]
df2.head()

# 특정 컬럼의 항목('서울') 추출
df2[df2['지역명'] == '서울' ]
df2['지역명'].unique()
df2.head()

# 파생변수 만들기
df2['차액'] = df2['예산현액'] - df2['지출액']
df2.head()

# 필요한 컬럼만 추출(2)
df2 = df2[['회계연도','분야명','차액']]
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3180 entries, 0 to 3179
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   No        3180 non-null   int64
 1   회계연도      3180 non-null   int64
 2   지역명       3180 non-null   object
 3   자치단체코드    3180 non-null   int64
 4   자치단체명_한글  3180 non-null   object
 5   분야코드      3180 non-null   int64
 6   분야명       3180 non-null   object
 7   집행일자      3180 non-null   int64
 8   예산현액      3180 non-null   float64
 9   지출액       3180 non-null   float64
dtypes: float64(2), int64(5), object(3)
memory usage: 248.6+ KB

   회계연도      분야명            차액
0  2022   일반공공행정 7100000000000
1  2022  공공질서및안전 1810000000000
2  2022       교육 3286000000000
3  2022    문화및관광  558000000000
4  2022       환경  680000000000

In [17]:
## 2023년 세출현황 데이터셋 전처리

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 과학적 표기법 해제
pd.options.display.float_format = '{:.0f}'.format

df3 = pd.read_csv("Practice Data/분야별 세출현황_2023.csv")
df3.info() #결측치 없음
df3.columns = df3.columns.str.strip()

df3 = df3[['회계연도','지역명','분야명','예산현액','지출액']]
df3.head()

# 특정 컬럼의 항목('서울') 추출
df3[df3['지역명'] == '서울' ]
df3['지역명'].unique()
df3.head()

# 파생변수 만들기
df3['차액'] = df3['예산현액'] - df3['지출액']
df3.head()

# 필요한 컬럼만 추출(2)
df3 = df3[['회계연도','분야명','차액']]
df3.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3180 entries, 0 to 3179
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   No        3180 non-null   int64
 1   회계연도      3180 non-null   int64
 2   지역명       3180 non-null   object
 3   자치단체코드    3180 non-null   int64
 4   자치단체명_한글  3180 non-null   object
 5   분야코드      3180 non-null   int64
 6   분야명       3180 non-null   object
 7   집행일자      3180 non-null   int64
 8    예산현액     3180 non-null   float64
 9    지출액      3180 non-null   float64
dtypes: float64(2), int64(5), object(3)
memory usage: 248.6+ KB

   회계연도      분야명            차액
0  2023   일반공공행정 8892210000000
1  2023  공공질서및안전 1341148000000
2  2023       교육 3522816000000
3  2023    문화및관광  541555000000
4  2023       환경  813102000000